[package]
name = "Regex"
version = "0.1.0"
authors = ["npnguyen99 <phucnguyen1999.nn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
